export default {
    path:'/movie',
    component:()=>import('@/components/Movie'),
    children:[
        {
            path:'/movie',
            redirect:'nowplaying'
        },
        {
            path:'city',
            component:()=>import('@/components/subcomponents/city')
        },
        {
            path:'nowplaying',
            component:()=>import('@/components/subcomponents/nowPlaying')
        },
        {
            path:'commingsoon',
            component:()=>import('@/components/subcomponents/commingSoon')
        },
        {
            path:'search',
            component:()=>import('@/components/subcomponents/search')
        },
        {
            path:'detail/1/:movieid',
            components:{
                default:()=>import('@/components/subcomponents/nowPlaying'),
                detail:()=>import('@/components/Movie/detail.vue')
            },
            props:{
                detail:true
            }
        },
        {
            path:'detail/2/:movieid',
            components:{
                default:()=>import('@/components/subcomponents/commingSoon'),
                detail:()=>import('@/components/Movie/detail.vue')
            },
            props:{
                detail:true
            }
        }
       
    ]
}